[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter-language = "0.1"
tree-sitter = "0.24"
tree-sitter-rust = "0.23"
tree-sitter-essence = { version = "0.1.0", path = "../tree-sitter-essence" }
conjure_core = { path = "../../crates/conjure_core" }

[lints]
workspace = true
