[workspace]
resolver = "2"

default-members = [
    "conjure_oxide",
    "crates/conjure_core",
    "solvers/kissat",
    "solvers/minion",
]

members = [
    "conjure_oxide",
    "crates/conjure_core",
    "solvers/kissat",
    "solvers/minion",
    "solvers/chuffed",
]

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
