[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-essence"
description = "WIP parser for essence"
version = "0.1.0"
keywords = ["incremental", "parsing", "tree-sitter", "essence"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Leia McAlister-Young", email = "l.mcalisteryoung@gmail.com" }]
requires-python = ">=3.9"
license.text = "Mozilla Public License"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/tree-sitter/tree-sitter-essence"

[project.optional-dependencies]
core = ["tree-sitter~=0.22"]

[tool.cibuildwheel]
build = "cp39-*"
build-frontend = "build"
