[package]
name = "conjure_core"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = "3.5.1"
strum = "0.26.1"
strum_macros = "0.26.1"
thiserror = "1.0.50"
conjure_ast_proc_macro = {path= "../conjure_ast_proc_macro"}

[lints]
workspace = true
