[package]
name = "conjure_core"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_with = "3.6.1"
strum = "0.26.1"
strum_macros = "0.26.1"
thiserror = "1.0.57"
enum_compatability_macro = {path= "../enum_compatability_macro"}
uniplate = {path = "../uniplate"}
uniplate_derive = {path = "../uniplate_derive"}

[lints]
workspace = true
