[package]
name = "conjure_core"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
serde_with = "3.4.0"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.50"

[lints]
workspace = true
