[package]
name = "conjure_core"
version = "0.0.1"
edition = "2021"

[dependencies]
conjure_rules_proc_macro = {path = "../conjure_rules_proc_macro"}
linkme = "0.3.25"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_with = "3.7.0"
strum = "0.26.2"
strum_macros = "0.26.2"
thiserror = "1.0.58"
derive_is_enum_variant = "0.1.1"
enum_compatability_macro = {path= "../enum_compatability_macro"}
uniplate = {path = "../uniplate"}
uniplate_derive = {path = "../uniplate_derive"}
log = "0.4.21"

[lints]
workspace = true
