[package]
name = "conjure_rules"
version = "0.1.0"
edition = "2021"

[dependencies]
conjure_macros = { path = "../conjure_macros" }
conjure_core = { path = "../conjure_core" }
linkme = "0.3.22"

[lints]
workspace = true
