[package]
name = "conjure_oxide"
version = "0.0.1"
edition = "2021"
default-run = "conjure_oxide"

# these are available inside build.rs
[build-dependencies]
walkdir = "2.4.0"

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.109"
serde_with = "3.4.0"
thiserror = "1.0.53"
minion_rs = {path = "../solvers/minion" }
anyhow = "1.0.78"
clap = { version = "4.4.12", features = ["derive"] }
strum_macros = "0.25.3"
strum = "0.25.0"
versions = "6.0.0"

[lints]
workspace = true
