[package]
name = "conjure_oxide"
version = "0.0.1"
edition = "2021"
default-run = "conjure_oxide"

# these are available inside build.rs
[build-dependencies]
walkdir = "2.5.0"

[dependencies]
conjure_core = { path = "../crates/conjure_core" }
uniplate = { git = "https://github.com/conjure-cp/conjure-oxide.git", rev = "0dc7090f0388d9a4fc0460d7d5fbf79da7854170" }
uniplate_derive = { git = "https://github.com/conjure-cp/conjure-oxide.git", rev = "0dc7090f0388d9a4fc0460d7d5fbf79da7854170" }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
serde_with = "3.8.1"
thiserror = "1.0.59"
minion_rs = { path = "../solvers/minion" }
anyhow = "1.0.82"
clap = { version = "4.5.3", features = ["derive"] }
strum_macros = "0.26.2"
strum = "0.26.2"
versions = "6.2.0"
linkme = "0.3.22"
walkdir = "2.5.0"
regex = "1.10.3"
log = "0.4.21"
structured-logger = "1.0.3"
schemars = "0.8.17"

[features]

unstable = []
unstable-solver-interface = ["unstable"]

[lints]
workspace = true
