# https://doc.rust-lang.org/cargo/guide/continuous-integration.html
# https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
name: "solvers/chuffed"

on:
  workflow_dispatch:
  push:
    branches:
      - main # run for pushes to the main branch
    paths:
      - solvers/chuffed/**
      - Cargo.*
      - .github/workflows/chuffed.yml
  pull_request:
    paths:
      - solvers/chuffed/**
      - Cargo.*
      - .github/workflows/chuffed.yml

env:
  rust_release: stable

jobs:
  ubuntu:
    name: "Chuffed: Ubuntu Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
            solvers/minion/vendor
            solvers/chuffed/vendor

          key: ${{ runner.os }}-${{ env.rust_release }}-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-${{ env.rust_release }}-

      - working-directory: ./solvers/chuffed
        run: rustup update ${{ env.rust_release }} && rustup default ${{ env.rust_release }}

      - working-directory: ./solvers/chuffed
        run: cargo build -vv

  mac:
    name: "Chuffed: Mac Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
            solvers/minion/vendor
            solvers/chuffed/vendor

          key: ${{ runner.os }}-${{ env.rust_release }}-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-${{ env.rust_release }}-

      - working-directory: ./solvers/chuffed
        run: rustup update ${{ env.rust_release }} && rustup default ${{ env.rust_release }}

      - working-directory: ./solvers/chuffed
        run: rustup target add aarch64-apple-darwin

      - working-directory: ./solvers/chuffed
        run: cargo build -vv

  tests:
    name: "Chuffed: Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
            solvers/minion/vendor
            solvers/chuffed/vendor

          key: ${{ runner.os }}-${{ env.rust_release }}-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-${{ env.rust_release }}-

      - working-directory: ./solvers/chuffed
        run: rustup update ${{ env.rust_release }} && rustup default ${{ env.rust_release }}

      - working-directory: ./solvers/chuffed
        run: cargo test
