  name: "tools/essence-feature-stats"
  on:
    push

  jobs:
    build:
      name: "tools/essence-feature-stats: Build the tool and clone EssenceCatalog repo"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up cache
          uses: actions/cache@v3
          with:
            path: |
