  name: "tools/essence-feature-stats"

  on:
    push

  env:
    ESSENCE_DIR: "~/essence-feature-stats/EssenceCatalog"
    CONJURE_DIR: "~/essence-feature-stats/conjure"
    ESSENCE_EXAMPLES_REPO: "https://github.com/conjure-cp/EssenceCatalog.git"
    CONJURE_REPO: "https://github.com/conjure-cp/conjure"
    GITHUB_PAGE_DIR: "~/essence-feature-stats/page"
    OUTPUT_PATH: "~/essence-feature-stats/page/table.html"
    KEYWORD_BLOCKLIST: "mInfo,finds,givens,enumGivens,enumLettings,lettings,
                        unnameds,strategyQ,Auto,Interactive,strategyA,trailCompact,
                        nameGenState,nbExtraGivens,representations,representationsTree,
                        originalDomains,trailGeneralised,trailVerbose,trailRewrites,
                        mLanguage,language,version,mStatements,Name,Declaration"

  jobs:
    generate:
      name: "tools/essence-feature-stats: Build the tool and clone EssenceCatalog repo"

      runs-on: ubuntu-latest

      strategy:
        matrix:
          python-version: ["3.11"]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install python dependencies
          run: pip install -r requirements.txt
          working-directory: ./tools/essence-feature-usage-stats

        - name: Run main.py
          run: python main.py
          working-directory: ./tools/essence-feature-usage-stats

        - name: Copy static files to the GitHub Page directory
          run: mkdir -p ${{ env.GITHUB_PAGE_DIR }} && cp -r ./web/static ${{ env.GITHUB_PAGE_DIR }}/
          working-directory: ./tools/essence-feature-usage-stats

        - name: Verify that the correct files were copied
          run: diff <(ls ./web/static) <(ls ${{ env.GITHUB_PAGE_DIR }}/static)
          working-directory: ./tools/essence-feature-usage-stats

        - name: Compress the GitHub Page directory into a tar archive
          run: tar -czvf archive.tar.gz -C ${{ env.GITHUB_PAGE_DIR }}
          working-directory: ./tools/essence-feature-usage-stats

        - name: Upload Tar Archive as a GitHub Pages artifact
          uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: archive.tar.gz
