# see: https://github.com/marketplace/actions/rust-rustfmt-check

name: "Formatting"

on:
  pull_request:
  push:

jobs:
  rust:
    name: "Check Rust Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check
