# https://doc.rust-lang.org/cargo/guide/continuous-integration.html
name: 'solvers/minion'
on:
  push:
    paths: 
      - 'solvers/minion/**'
  pull_request:
    paths: 
      - 'solvers/minion/**'
  workflow_dispatch:

jobs:
  ubuntu:
    name: 'solvers/minion: Ubuntu Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - working-directory: ./solvers/minion
        run: rustup update stable && rustup default stable

      - working-directory: ./solvers/minion
        run: cargo build --verbose

  mac:
    name: 'solvers/minion: Mac Build'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - working-directory: ./solvers/minion
        run: rustup update stable && rustup default stable

      - working-directory: ./solvers/minion 
        run: rustup target add aarch64-apple-darwin

      - working-directory: ./solvers/minion
        run: cargo build --verbose

  tests:
    name: 'solvers/minion: Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - working-directory: ./solvers/minion
        run: rustup update stable && rustup default stable

      - working-directory: ./solvers/minion
        run: cargo test



      


