name: "conjure-oxide"

on:
  push:
    branches:
      - main # run for pushes to the main branch. other branches need to create a PR if they want testing.
    paths: 
      - conjure_oxide/**
      - Cargo.*
      - .github/workflows/oxide.yml
  pull_request:
    paths: 
      - conjure_oxide/**
      - Cargo.*
      - .github/workflows/oxide.yml
  workflow_dispatch:


jobs:

  Job:

    strategy:
      matrix:
        rust_release:
          - stable
          - nightly
        conjure_version:
          - v2.5.1
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            release_suffix: linux
          - os: macos-latest
            release_suffix: macos-intel

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: 
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
            solvers/minion/vendor
            solvers/chuffed/vendor

          key: ${{ runner.os }}-${{ matrix.rust_release }}-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-${{ matrix.rust_release }}

      - working-directory: ./conjure_oxide
        run: rustup update ${{ matrix.rust_release }} && rustup default ${{ matrix.rust_release }}

      - working-directory: ./conjure_oxide
        run: cargo build -vv

      - working-directory: ./conjure_oxide
        run: |
          wget https://github.com/conjure-cp/conjure/releases/download/${{ matrix.conjure_version }}/conjure-${{ matrix.conjure_version }}-${{ matrix.release_suffix }}-with-solvers.zip
          unzip conjure-${{ matrix.conjure_version }}-linux-with-solvers.zip
          echo "$(pwd)/conjure-${{ matrix.conjure_version }}-linux-with-solvers" >> ${GITHUB_PATH}

      - working-directory: ./conjure_oxide
        run: cargo test
