name: "conjure-oxide"

on:
  push:
    branches:
      - main # run for pushes to the main branch
    paths: 
      - conjure_oxide/**
      - Cargo.*
      - .github/workflows/oxide.yml
  pull_request:
    paths: 
      - conjure_oxide/**
      - Cargo.*
      - .github/workflows/oxide.yml
  workflow_dispatch:

env:
  rust_release: stable

jobs:

  Job:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: 
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
            solvers/minion/vendor
            solvers/chuffed/vendor

          key: ${{ runner.os }}-${{ env.rust_release }}-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-${{ env.rust_release }}

      - working-directory: ./conjure_oxide
        run: rustup update ${{ env.rust_release }} && rustup default ${{ env.rust_release }}

      - working-directory: ./conjure_oxide
        run: rustup target add aarch64-apple-darwin
        if: runner.os == 'macOS'

      - working-directory: ./conjure_oxide
        run: cargo build -vv

      - working-directory: ./conjure_oxide
        run: |
          wget https://github.com/conjure-cp/conjure/releases/download/v2.5.1/conjure-v2.5.1-linux-with-solvers.zip
          unzip conjure-v2.5.1-linux-with-solvers.zip
          echo "$(pwd)/conjure-v2.5.1-linux-with-solvers" >> ${GITHUB_PATH}

      - working-directory: ./conjure_oxide
        run: cargo test
