name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been automatically closed because it has been inactive for 30 days. Please reopen if you think this issue is still relevant.'
          days-before-issue-stale: 30
          days-before-issue-close: 0
          stale-pr-message: 'The pull request is marked as stale because it has been inactive for 30 days. If there is no new activity it will be automatically closed in 5 days.'
          stale-pr-label: stale
          days-before-pr-stale: 30
          days-before-pr-close: 5
